listing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('listings.urls')),
]

listings/urls.py
from django.urls import path
from . import views

app_name = "listings"

urlpatterns = [
    path('', views.index, name='index'),
    path('listings', views.all_listings, name='listings'),
    path('new_listing/', views.new_listing, name='new_listing'),
]

listings/models.py
from django.db import models
from django.utils.timezone import now
from datetime import datetime

# Create your models here.


class Listings(models.Model):

    class SaleType(models.TextChoices):
        PICKUP = "Available for pickup"
        SHIP = "Available for shipping"

    class ConditionType(models.TextChoices):
        USED = "Used"
        NEW = "New"

    class ProductType(models.TextChoices):
        BIKE = "Bike"
        PARTS = "Parts"
        MODELS = "Models"
        OTHER = "Other"

    title = models.CharField(max_length=100)
    condition = models.CharField(
        max_length=50, choices=ConditionType.choices, default=ConditionType.USED)
    product_type = models.CharField(
        max_length=50, choices=ProductType.choices, default=ProductType.BIKE)
    sale_type = models.CharField(
        max_length=50, choices=SaleType.choices, default=SaleType.SHIP)
    price = models.FloatField()
    address = models.CharField(max_length=100)
    city = models.CharField(max_length=25)
    state = models.CharField(max_length=25)
    zipcode = models.CharField(max_length=25)
    main_photo = models.ImageField()
    photo_1 = models.ImageField()
    photo_2 = models.ImageField(blank=True)
    list_date = models.DateTimeField(default=now)
    contact_email = models.CharField(max_length=50)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Listings"

listings/forms.py
from django import forms
from .models import Listings


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listings
        fields = ['title', 'condition', 'product_type', 'sale_type', 'price', 'main_photo', 'photo_1',
                  'photo_2', 'city', 'state', 'zipcode', 'contact_email', 'list_date']

listings/views.py
from django.shortcuts import render, redirect
from .models import Listings
from .forms import ListingForm

# Create your views here.


def index(request):
    return render(request, "listings/index.html")


def all_listings(request):
    all_listings = Listings.objects.order_by('-list_date')
    context = {'all_listings': all_listings}
    return render(request, "listings/all-listings.html", context)


def new_listing(request):
    if request.method != 'POST':
        form = ListingForm()
    else:
        form = ListingForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('listings:listings')

    context = {'form': form}
    return render(request, 'listings/new-listing.html', context)

listings/templates/listings/all-listings.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Listings</title>
</head>

<body>
    <h1>Listings</h1>
    <div class="listing">
        <div class="card">
            {% for listing in all_listings %}
            <p><b>Title:</b> {{ listing.title }}</p>
            <p><b>Condition:</b> {{ listing.condition }}</p>
            <p><b>Sale Type:</b> {{ listing.sale_type }}</p>
            <p><b>Price:</b> &#8377; {{ listing.price|floatformat:2 }}</p>
            <p><b>Location:</b> {{ listing.city }}, {{ listing.state }}</p>
            <p><b>Post Date:</b> {{ listing.list_date }}</p>
            <ul>
                <a class="btn" href="">View Listing</a>
            </ul>
            <hr />
            {% empty %}
            <h3>No listings found. Try again.</h3>
            {% endfor %}
        </div>
    </div>
</body>

</html>

listings/templates/listings/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy Used/New Items</title>
</head>

<body>
    <h1>Product Listings</h1>
    <p>Homepage</p>
</body>

</html>

listings/templates/listings/new-listing.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>New</title>
</head>

<body>
    <h1>NEW LISTING</h1>

    <form action="{% url 'listings:new_listing' %}" method='post' enctype="multipart/form-data">
        <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
        </div>
        <button type="submit" class="btn">Create Listing</button>
    </form>
</body>

</html>